export enum IPC_EVENT_NAMES {
  WINDOW_SHOW = 'WINDOW_SHOW',
  SET_ALWAYS_ON_TOP = 'SET_ALWAYS_ON_TOP',
  BROWSER_WINDOW_METHOD_SYNC = 'BROWSER_WINDOW_METHOD_SYNC',
  BROWSER_WINDOW_METHOD_ASYNC = 'BROWSER_WINDOW_METHOD_ASYNC',
  GET_TOKEN = 'GET_TOKEN',
  CHANGE_EASY_NOTE_MODE = 'CHANGE_EASY_NOTE_MODE',
  FLOATING_WINDOW_MOVE = 'FLOATING_WINDOW_MOVE',
  CLOSE_EASY_NOTE = 'CLOSE_EASY_NOTE',
  SET_EXPAND_MODE = 'SET_EXPAND_MODE',
  GET_EXPAND_MODE = 'GET_EXPAND_MODE',
  SET_DEFAULT_ACTION = 'SET_DEFAULT_ACTION',
  GET_DEFAULT_ACTION = 'GET_DEFAULT_ACTION',
  // 笔记相关事件
  CREATE_NOTE = 'CREATE_NOTE',
  READ_NOTE = 'READ_NOTE',
  UPDATE_NOTE = 'UPDATE_NOTE',
  DELETE_NOTE = 'DELETE_NOTE',
  LIST_NOTES = 'LIST_NOTES',
  UPLOAD_IMAGE = 'UPLOAD_IMAGE',
}

export enum WEB_PAGE_EVENT_NAMES {
  ON_NOTE_CLOSE = 'ON_NOTE_CLOSE', // 小记主窗口关闭时间
}
